substitutions:
    _PROJECT_ID: "cloud-engineer-dev1"
    _ARTIFACT_REGISTRY_REPO: "test-and-build"  
    

steps:
    # Install dependencies
    - name: 'python'
      entrypoint: 'python'
      args: ['-m', 'pip', 'install', '--upgrade', 'pip']
    - name: python
      entrypoint: python
      args: ['-m', 'pip', 'install', 'build', 'pytest', 'Flask', '--user']

    - id: Check Path
      name: 'python'
      entrypoint: sh
      args:
        - -c
        - |
          pwd && ls -la

    # Docker Build
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 
            'gcr.io/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}']

    # Docker push to Google Artifact Registry
    # - name: 'gcr.io/cloud-builders/docker'
    #   args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}']

timeout: 10800s
options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE
