substitutions:
    _PROJECT_ID: "cloud-engineer-dev1"
    _ARTIFACT_REGISTRY_REPO: "https://us-central1-python.pkg.dev/cloud-engineer-dev1/test-and-build"  
    

steps:
    # Install dependencies
    - name: 'python'
      entrypoint: 'python'
      args: ['-m', 'pip', 'install', '--upgrade', 'pip']
    - name: python
      entrypoint: python
      args: ['-m', 'pip', 'install', 'build', 'pytest', 'Flask', '--user']

    # Docker Build
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 
            'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}', '.']

    # Docker push to Google Artifact Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}']

timeout: 10800s
options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE
